spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wer
    username: postgres
    password: user
  # JPA properties
  jpa:
    database-platform: org.hibernate.dialect.PostgresSQLDialect

    hibernate:
      ddl-auto: create
      # When you launch the application for the first time - switch "none" at "create"

    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true

  hikari:
    maximum-pool-size: 10
  application:
    name: wer

  main:
    allow-circular-references: true